<!-- include file: menu.inc; start -->
<ul class="linklist">
<li><a href="index.html" accesskey="h" title="Subhabrata Mukherjee MPII Homepage" id="hp-index">Subhabrata Mukherjee:</a>
<ul>
<li><a href="index.html#research" accesskey="r" title="Research Interests" id="hp-research"><span class="ak">R</span>esearch Interests</a></li>
<li><a href="index.html#news" accesskey="n" title="Recent News" id="hp-news"><span class="ak">R</span>ecent News</a></li>
<li><a href="index.html#positions" accesskey="o" title="Positions of Subhabrata Mukherjee" id="hp-positions">Recent P<span class="ak">o</span>sitions</a></li>
<li><a href="index.html#publications" accesskey="p" title="Publications of Subhabrata Mukherjee" id="hp-publications"><span class="ak">R</span>esearch Areas, Publications</a>
<li><a href="index.html#talks" accesskey="t" title="Talks" id="hp-talks"><span class="ak">T</span>alks</a></li>
<li><a href="index.html#datasets" accesskey="d" title="Datasets for Public Download" id="hp-datasets"><span class="ak">D</span>atasets</a></li>
<li><a href="index.html#reviewer" accesskey="r" title="External Reviewer" id="hp-reviewer"><span class="ak">E</span>xternal Reviewer</a></li>
<li><a href="index.html#education" accesskey="e" title="Education of Subhabrata Mukherjee" id="hp-education"><span class="ak">E</span>ducation</a></li>
</ul>
</li>
<!-- CHANGE HERE: Put your own menu items here. They can also point to different html pages. --> 
<!-- Make sure to highlight the page you are on using the style section on top of that page -->
</ul>
<!-- include file: menu.inc; end -->
